<?php

namespace BtoB\SocialNetwork\EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Repositorio de invitacion
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends EntityRepository
{
}
