<?php

namespace BtoB\SocialNetwork\EntityBundle\Repository;

use BtoB\SocialNetwork\EntityBundle\Entity\User;
use BtoB\SocialNetwork\CoreBundle\Doctrine\ORM\EntityRepository;

/**
 * Repositorio de notificaciones
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    /**
     * Retorna las notificaciones de un usuario
     * @param \BtoB\SocialNetwork\EntityBundle\Entity\User $user
     * @return type
     */
    function findNotificationsToUser(User $user)
    {
        $qb = $this->createQueryBuilder("n");
        $qb
            ->addSelect("f")
            ->addSelect("t")
            ->innerJoin("n.from", 'f')
            ->innerJoin("n.to", 't')
            ->andWhere("n.to = :user")
            ->andWhere("n.from != :user")
            ->orderBy('n.id','DESC')
            ->setParameter('user', $user)
            ;
        return $this->getPaginator($qb);
    }
}
