<?php

namespace BtoB\SocialNetwork\EntityBundle\Repository;

use BtoB\SocialNetwork\CoreBundle\Doctrine\ORM\EntityRepository;

/**
 * LikeCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardCommentRepository extends EntityRepository
{
    function findRewardsCommentByUser(\BtoB\SocialNetwork\EntityBundle\Entity\User $user,array $criteria = array(),array $sorting = array()) {
        $qb = $this->getQueryBuilder();
        $qb
                ->select("rc")
                ->addSelect("c")
                ->addSelect("u")
                ->innerJoin("rc.comment", 'c')
                ->innerJoin('c.byUser', 'u')
                ->andWhere('u.id = :user')
                ->setParameter('user', $user)
                ->orderBy('rc.id','DESC')
            ;
        $criteria = new \Doctrine\Common\Collections\ArrayCollection($criteria);
        if(($userName = $criteria->remove('username'))){
            $qb->andWhere($qb->expr()->like("u.username","'%".$userName."%'"));
        }
        if(($dateStart = $criteria->remove('dateStart'))){
            $qb->andWhere('rc.time >= :dateStart')
            ->setParameter('dateStart', $dateStart)
            ;
        }
        if(($dateEnd = $criteria->remove('dateEnd'))){
            $qb->andWhere('rc.time <= :dateEnd')
            ->setParameter('dateEnd', $dateEnd)
            ;
        }
        if(($dateEnd = $criteria->remove('dateEnd'))){
            $qb->andWhere('rc.time <= :dateEnd')
            ->setParameter('dateEnd', $dateEnd)
            ;
        }
        $this->applySorting($qb,$sorting);
        
        return $this->getPaginator($qb);
    }
    
    protected function getAlias() {
        return 'rc';
    }
}
