BtoB\SocialNetwork\EntityBundle\Entity\Relation:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [id]
        status:
            expose: true
            groups: [api_list]
        time:
            expose: true
            groups: [api_list]
        leader:
            expose: true
            groups: [api_relation]
        subscriber:
            expose: true
            groups: [api_relation]